name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Determine if PR should be merged
      id: determine-merge
      run: |
        ALLOWED_USERS=("yindushenwen" "linxunxr" "c386522459" "Sunny-316" "thfgjy" "stupchen" "MaoXiaoone" "ouzechang" "polo3584" "YiQingZi")
        PR_AUTHOR=$(jq -r .pull_request.user.login < "$GITHUB_EVENT_PATH")

        if [[ " ${ALLOWED_USERS[*]} " =~ " ${PR_AUTHOR} " ]]; then
          echo "PR author ${PR_AUTHOR} is allowed. Proceeding to merge."
          echo "MERGE=true" >> $GITHUB_ENV
        else
          echo "PR author ${PR_AUTHOR} is not allowed to auto-merge."
          echo "MERGE=false" >> $GITHUB_ENV

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh -y

    - name: Merge PR
      if: env.MERGE == 'true'
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
