name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Determine if PR should be merged
      id: determine-merge
      run: |
        ALLOWED_USERS=("yindushenwen" "linxunxr" "c386522459" "Sunny-316" "thfgjy" "stupchen" "MaoXiaoone" "ouzechang" "polo3584" "YiQingZi")
        PR_AUTHOR=$(jq -r .pull_request.user.login < "$GITHUB_EVENT_PATH")

        MERGE=false
        for user in "${ALLOWED_USERS[@]}"; do
          if [ "$user" == "$PR_AUTHOR" ]; then
            MERGE=true
            break
          fi
        done

        echo "MERGE=$MERGE" >> $GITHUB_ENV
        if [ "$MERGE" == "true" ]; then
          echo "PR author ${PR_AUTHOR} is allowed. Proceeding to merge."
        else
          echo "PR author ${PR_AUTHOR} is not allowed to auto-merge."
        fi

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://github.com/cli/cli/releases/download/v2.49.2/gh_2.49.2_linux_amd64.tar.gz -o ghcli.tar.gz
        tar -xzf ghcli.tar.gz
        sudo mv gh_2.49.2_linux_amd64/bin/gh /usr/local/bin/
        gh --version

    - name: Merge PR
      if: env.MERGE == 'true'
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
