name: Backup Main Branch

on:
  push:
    branches: [ main ]

jobs:
  backup:
    name: Backup Main Branch
    runs-on: ubuntu-latest
    env:
      BACKUP_DATETIME: ${{ steps.datetime.outputs.datetime }}
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get Current Datetime
        id: datetime
        run: echo "::set-output name=datetime::$(date '+%Y-%m-%d_%H-%M-%S')"

      - name: Archive Main Branch Code
        run: |
          git archive --format=tar.gz --output=main_backup_${BACKUP_DATETIME}.tar.gz HEAD

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Backup Branch
        run: |
          git checkout -b backup || git checkout backup
          mkdir -p backups
          mv main_backup_${BACKUP_DATETIME}.tar.gz backups/
          git add -A
          git commit -m "Auto backup main branch code"
          git push origin backup

      - name: Switch Back to Main Branch
        run: git checkout main
