name: Backup Main Branch

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Archive main branch as tar.gz
      run: |
        tar -czf main_backup_$(date +"%Y%m%d").tar.gz *
      working-directory: ${{ github.workspace }}

    - name: Create and push backup branch
      run: |
        git config --local user.email "miaogongzi0227@gmail.com"
        git config --local user.name "mgz0227"
        git branch -D backup || true
        git checkout -b backup
        git add main_backup_$(date +"%Y%m%d").tar.gz
        git commit -m "Backup main branch as of $(date +"%Y-%m-%d")"
        git push origin backup
