name: Backup Master Branch

on:
  push:
    branches: [ master ]

jobs:
  backup:
    name: Backup Master Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Create Backup Directory
        run: mkdir -p backups/master

      - name: Copy Master Branch Code
        run: cp -r * backups/master

      - name: Archive Master Branch Code
        run: |
          datetime=$(date '+%Y-%m-%d_%H-%M-%S')
          tar -zcf master_backup_$datetime.tar.gz -C backups/master .

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Backup Branch
        run: |
          git checkout -b backup || git checkout backup
          git rm -rf .
          git add -A
          git commit -m "Auto backup master branch code"
          git push origin backup

      - name: Switch Back to Master Branch
        run: git checkout master
