name: Backup Main Branch

on:
  push:
    branches: [ main ]

jobs:
  backup:
    name: Backup Main Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create Backup Directory
        run: mkdir -p backups/main

      - name: Copy Main Branch Code
        run: cp -r * backups/main

      - name: Archive Main Branch Code
        run: |
          datetime=$(date '+%Y-%m-%d_%H-%M-%S')
          tar -zcf main_backup_$datetime.tar.gz -C backups/main .

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Backup Branch
        run: |
          git checkout -b backup || git checkout backup
          git rm -rf .
          git add -A
          git commit -m "Auto backup main branch code"
          git push origin backup

      - name: Switch Back to Main Branch
        run: git checkout main
